version: '3.7'
services:
  db:
    image: postgres:10.13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "7001:5432"
  redis:
    image: redis:6.0.2-alpine
    ports:
      - "7002:6379"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
volumes:
  myapp-postgres:
  myapp-redis:
